{"uuid": "eecc50ba-e953-4fcb-a3f8-d2b5aa5a95b2", "counter": 12, "stdout": "\u001b[0;31mfatal: [192.168.38.8]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python3\"}, \"changed\": true, \"cmd\": [\"ip\", \"link\", \"add\", \"ne_in_S1_br\", \"type\", \"bridge\"], \"delta\": \"0:00:00.009641\", \"end\": \"2024-04-22 04:19:00.089673\", \"msg\": \"non-zero return code\", \"rc\": 2, \"start\": \"2024-04-22 04:19:00.080032\", \"stderr\": \"RTNETLINK answers: File exists\", \"stderr_lines\": [\"RTNETLINK answers: File exists\"], \"stdout\": \"\", \"stdout_lines\": []}\u001b[0m", "start_line": 122, "end_line": 123, "runner_ident": "2dc4a0e3-911d-428d-b0fb-3bd4e6ddba27", "event": "runner_on_failed", "pid": 3880438, "created": "2024-04-22T04:19:00.171868", "parent_uuid": "52540038-3809-c03d-7d2c-000000000006", "event_data": {"playbook": "/home/vmadm/demo/RapidServe/southbound/deploy_subnet.yaml", "playbook_uuid": "9c5d1907-5127-4f4a-9a7d-bbec599053c6", "play": "Deploy subnet Infrastructure with bridges and Veth Pairs", "play_uuid": "52540038-3809-c03d-7d2c-000000000002", "play_pattern": "hostvms", "task": "Create bridges for each subnet", "task_uuid": "52540038-3809-c03d-7d2c-000000000006", "task_action": "command", "resolved_action": "ansible.builtin.command", "task_args": "", "task_path": "/home/vmadm/demo/RapidServe/southbound/deploy_subnet.yaml:16", "host": "192.168.38.8", "remote_addr": "192.168.38.8", "res": {"changed": true, "stdout": "", "stderr": "RTNETLINK answers: File exists", "rc": 2, "cmd": ["ip", "link", "add", "ne_in_S1_br", "type", "bridge"], "start": "2024-04-22 04:19:00.080032", "end": "2024-04-22 04:19:00.089673", "delta": "0:00:00.009641", "msg": "non-zero return code", "invocation": {"module_args": {"_raw_params": "ip link add ne_in_S1_br type bridge", "_uses_shell": false, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}, "stdout_lines": [], "stderr_lines": ["RTNETLINK answers: File exists"], "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "_ansible_no_log": null}, "start": "2024-04-22T04:18:58.979873", "end": "2024-04-22T04:19:00.171205", "duration": 1.191332, "ignore_errors": null, "event_loop": null, "uuid": "eecc50ba-e953-4fcb-a3f8-d2b5aa5a95b2"}}